version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ../
    volumes:
      - .:/trello-clone
    ports:
      - "80:3000"
    depends_on:
      - db
